spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.2.1:3306/isa
    username: root
    password: isa@sql.com
    drive-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.isa.lucky.pet.dao
  mapper-locations: classpath:mapper/*Mapper.xml
