spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.0.75.1:3306/isa
    username: root
    password: Huajl333
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.isa.lucky.pet.dao
  mapper-locations: classpath:mapper/*.xml
